language: node_js
node_js:
  - '5.7'
env:
  - NODE_ENV=travisci
services:
  - mongodb
before_install:
  - npm install -g bower grunt-cli mocha
before_script:
  - node ./bin/www &
  - sleep 20
script:
  - mocha
notifications:
  email:
    on_success: never
    on_failure: change
